# version: '3.9'
# services:
#   nestapp:
#     build: ./
#     ports:
#       - "3001:3000"
#     env_file:
#       - .env.development
#     depends_on:
#       - postgresdb

#   postgresdb:
#     image: postgres
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#     env_file:
#       - .env.development

# volumes:
#   pgdata:



services:
  nestapp:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/src
    env_file:
      - .env.development
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env.development

volumes:
  pgdata: