services:
  nestapp:
    # build: 
    #   context: .
    #   dockerfile: Dockerfile
    image: agustintaborda/ecommerce-m4:latest
    ports:
      - "3000:3000"
    volumes:
      - .:/src
    env_file:
      - .env.development
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env.development

volumes:
  pgdata: